using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MODEL
{
    public class Usuario
    {
        public int CodUsu { get; set;}
        public string NomeUsu { get; set; }
        public string Usu { get; set; }
        public string Senha { get; set; }
        public DateTime DataNasc { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
    }
}
